### ISSUE TITLE
Condition missing in Control Group

### ISSUE THREAD

**Issue by matared** [hackal/Exp#32]
ISSUE: In count down banner for example, conditions are not even in CG and variant. If banner show is tracked only until 15:00 for variant, for CG is show tracked also after 15:00. Of course we know how to handle it, but if consultant will use this template, I doubt he/she will know how to do that. 

UC: I have banner shown from 0:00 to 15:00 every day on certain category pages.

**Comment by lukasotocerny** [comment]
Functinality mentioned in my comment above is addressed in PR https://github.com/hackal/Exp/pull/34

**Comment by lukasotocerny** [comment]
PR https://github.com/hackal/Exp/pull/34 merged

**Comment by hackal** [comment]
This is still not resolved. Current `contro_group: true` setting does nothing. 
Control group should be triggered exactly the same way as other groups. Instead of displaying the banner and track show, it should just track show.

**Comment by hackal** [comment]
#73 Fixed here

**Comment by hackal** [comment]
@rkluvanec fixed, merged and released
